//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _BookNeT_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Borrowing = new HashSet<Borrowing>();
            this.Purchases = new HashSet<Purchases>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.UserLibrary = new HashSet<UserLibrary>();
            this.WaitingList = new HashSet<WaitingList>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> YearOfPublication { get; set; }
        public string Format { get; set; }
        public string Genre { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> BorrowPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> IsBorrowable { get; set; }
        public Nullable<int> AgeRestriction { get; set; }
        public Nullable<bool> IsDiscounted { get; set; }
        public Nullable<System.DateTime> DiscountEndDate { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public string Status { get; set; }
        public string ImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrowing> Borrowing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLibrary> UserLibrary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingList> WaitingList { get; set; }
    }
}
